# Generated by Django 4.2.11 on 2026-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_tienda_pedido_tienda'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienda',
            name='bodega_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
