# Generated by Django 6.0.6 on 2026-06-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_tienda_pedido_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='latitud_entrega',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud_entrega',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
