# Generated by Django 4.2.11 on 2026-06-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_tienda_pedido_direccion_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
