# Generated by Django 6.0.3 on 2026-05-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_tienda_bodega_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='direccion_entrega',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='pedido',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
