# Generated by Django 4.2.11 on 2026-06-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_empresa_rut_pedido_latitud_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='empresa_rut',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='tienda',
            name='empresa_rut',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
