# Generated by Django 4.2.11 on 2026-06-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_pedido_empresa_rut_tienda_empresa_rut'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='bodega_origen_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID de bodega si origen_despacho=bodega', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='codigo_validacion',
            field=models.CharField(blank=True, help_text='Código de 6 dígitos para retirar en tienda/bodega', max_length=6),
        ),
        migrations.AddField(
            model_name='pedido',
            name='origen_despacho',
            field=models.CharField(choices=[('tienda', 'Despacho desde tienda'), ('bodega', 'Despacho desde bodega')], default='tienda', max_length=10),
        ),
    ]
