from django.urls import path
from .views import (
    InventarioListView, InventarioDetailView,
    PedidosListView, PedidosDetailView,
    BodegasListView, BodegasDetailView, BodegaEspacioView,
    TiendasListView, TiendasDetailView,
    DashboardView,
    EnviosListView, EnviosDetailView,
    EnviosEstadoView, EnviosPosicionView, EnviosRutaView,
    EnviosEnCursoView, EnviosPorPedidoView,
    EnviosCercanosView, EnvioTomarView, EnvioValidarPickupView, EnvioCompletarEntregaView,
    ParadaEstadoView,
    ConductoresListView, ConductoresDetailView,
)
from .cloudinary_views import FotoEntregaView, SubirImagenProductoView

urlpatterns = [
    path('inventario/',                        InventarioListView.as_view()),
    path('inventario/<pk>/',                   InventarioDetailView.as_view()),
    path('inventario/<int:pk>/imagen/',        SubirImagenProductoView.as_view()),
    path('pedidos/',                           PedidosListView.as_view()),
    path('pedidos/<pk>/',                      PedidosDetailView.as_view()),
    path('bodegas/',                           BodegasListView.as_view()),
    path('bodegas/<pk>/',                      BodegasDetailView.as_view()),
    path('bodegas/<int:pk>/espacio/',          BodegaEspacioView.as_view()),
    path('tiendas/',                           TiendasListView.as_view()),
    path('tiendas/<pk>/',                      TiendasDetailView.as_view()),
    path('dashboard/',                         DashboardView.as_view()),
    path('envios/',                            EnviosListView.as_view()),
    path('envios/<pk>/',                       EnviosDetailView.as_view()),
    path('envios/<int:pk>/estado/',            EnviosEstadoView.as_view()),
    path('envios/<int:pk>/posicion/',          EnviosPosicionView.as_view()),
    path('envios/<int:pk>/ruta/',              EnviosRutaView.as_view()),
    path('envios/<int:pk>/foto-entrega/',      FotoEntregaView.as_view()),
    path('envios/cercanos/',                   EnviosCercanosView.as_view()),
    path('envios/<int:pk>/tomar/',             EnvioTomarView.as_view()),
    path('envios/<int:pk>/validar-pickup/',    EnvioValidarPickupView.as_view()),
    path('envios/<int:pk>/completar/',         EnvioCompletarEntregaView.as_view()),
    path('envios/en-curso/',                   EnviosEnCursoView.as_view()),
    path('envios/pedido/<pedido_id>/',         EnviosPorPedidoView.as_view()),
    path('paradas/<pk>/estado/',               ParadaEstadoView.as_view()),
    path('conductores/',                       ConductoresListView.as_view()),
    path('conductores/<pk>/',                  ConductoresDetailView.as_view()),
]