# Generated by Django 4.2.11 on 2026-06-09 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=300)),
                ('nombre_comercial', models.CharField(blank=True, max_length=300)),
                ('giro', models.CharField(blank=True, max_length=300)),
                ('giro_codigo', models.CharField(blank=True, max_length=20)),
                ('region', models.CharField(blank=True, max_length=200)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_representante', models.CharField(blank=True, max_length=200)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('repartidor', 'Repartidor')], default='admin', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='api.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'perfil_usuario',
            },
        ),
    ]
