# Generated by Django 4.2.11 on 2026-06-29 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_rut', models.CharField(blank=True, db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('patente', models.CharField(max_length=10)),
                ('disponible', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_rut', models.CharField(blank=True, db_index=True, max_length=20)),
                ('pedido_id', models.PositiveIntegerField()),
                ('repartidor_id', models.PositiveIntegerField(blank=True, help_text='ID del PerfilUsuario (repartidor) asignado', null=True)),
                ('tipo', models.CharField(choices=[('ESTANDAR', 'Estándar'), ('EXPRESS', 'Express'), ('PROGRAMADO', 'Programado')], default='ESTANDAR', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_RUTA', 'En ruta'), ('COMPLETADO', 'Completado'), ('FALLIDO', 'Fallido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('origen_nombre', models.CharField(default='Bodega Central', max_length=300)),
                ('origen_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('origen_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destino_nombre', models.CharField(max_length=300)),
                ('destino_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('destino_lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('pos_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pos_lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('pos_actualizada', models.DateTimeField(blank=True, null=True)),
                ('ruta_geojson', models.JSONField(blank=True, null=True)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duracion_min', models.PositiveIntegerField(blank=True, null=True)),
                ('codigo_validacion', models.CharField(blank=True, help_text='Código de 6 dígitos para pickup', max_length=6)),
                ('foto_entrega_url', models.URLField(blank=True, help_text='URL de Cloudinary con foto de entrega', null=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios', to='envios.conductor')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('pedido_id', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=400)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_CAMINO', 'En camino'), ('LLEGADO', 'Llegado'), ('ENTREGADO', 'Entregado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('llegada_real', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='envios.envio')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='EventoRuta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('POSICION', 'Actualización de posición'), ('ESTADO', 'Cambio de estado'), ('INCIDENTE', 'Incidente'), ('NOTA', 'Nota')], max_length=20)),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='envios.envio')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
