# Generated by Django 4.2.11 on 2026-06-29 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodega',
            name='capacidad_volumen_cm3',
            field=models.FloatField(default=0, help_text='Capacidad total en cm³'),
        ),
        migrations.AddField(
            model_name='bodega',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bodega',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='volumen_cm3',
            field=models.FloatField(default=0, help_text='Volumen unitario en cm³ (alto × ancho × largo)'),
        ),
    ]
